version: "3"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - app-network
networks:
  app-network:
    name: app-network
    external: true